### ISSUE TITLE
미니언 체력이 0보다 낮을 때 맞은 투사체 양만큼 골드를 버는 문제

### ISSUE THREAD

**Issue by yoon-H** [SR-PLUM/SidheRigel#94]
발생 상황

1.  미니언을 공격함.
2. Cold를 이용해서 미니언 체력을 다 깎음.
3. Q 스킬로 공격하니 그 수만큼 골드가 들어왔음.

**Comment by Seobok** [comment]
https://github.com/SR-PLUM/SidheRigel/commit/d9cf68b13a1996fd9c4152da1bb2fde9fd96bc6b
